object Libraries {
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val coil = "io.coil-kt:coil:${Versions.coil}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraint_layout}"
    const val core = "androidx.core:core-ktx:${Versions.core_ktx}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val jodaTime = "joda-time:joda-time:${Versions.joda}"
    const val koinAndroid = "io.insert-koin:koin-android:${Versions.koin}"
    const val koinCore = "io.insert-koin:koin-core:${Versions.koin}"
    const val koinNavigation = "io.insert-koin:koin-androidx-navigation:${Versions.koin}"
    const val koinWork = "io.insert-koin:koin-androidx-workmanager:${Versions.koin}"
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.kotlin}"
    const val lifecycleCompiler = "androidx.lifecycle:lifecycle-compiler:${Versions.lifecycle_ktx}"
    const val lifecycleLivedata = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycle_ktx}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle_ktx}"
    const val lifecycleViewmodel ="androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle_ktx}"
    const val localization = "com.akexorcist:localization:${Versions.localization}"
    const val materialDesign = "com.google.android.material:material:${Versions.material}"
    const val moshi = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    const val moshiCodeGen = "com.squareup.moshi:moshi-kotlin-codegen:${Versions.moshi}"
    const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation}"
    const val navigationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val paging = "androidx.paging:paging-runtime:${Versions.paging}"
    const val recyclerView = "androidx.recyclerview:recyclerview:${Versions.recycler_view}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitMoshiConverter = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    const val room = "androidx.room:room-ktx:${Versions.room}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.room}"
    const val swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.swipe}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val work = "androidx.work:work-runtime-ktx:${Versions.work}"

    const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espresso_core}"
    const val jUnit ="junit:junit:${Versions.junit}"
    const val jUnitExt = "androidx.test.ext:junit:${Versions.ext_junit}"
}
