object Versions {
    const val appcompat = "1.4.1"
    const val coil = "2.0.0-rc03"
    const val constraint_layout = "2.1.3"
    const val core_ktx = "1.7.0"
    const val coroutines = "1.6.1"
    const val espresso_core = "3.4.0"
    const val ext_junit = "1.1.3"
    const val joda = "2.10.14"
    const val junit = "4.13.2"
    const val koin = "3.2.0-beta-1"
    const val kotlin = "1.6.21"
    const val lifecycle_ktx = "2.4.1"
    const val localization = "1.2.11"
    const val material = "1.5.0"
    const val moshi = "1.13.0"
    const val navigation = "2.4.2"
    const val paging = "3.1.1"
    const val recycler_view = "1.2.1"
    const val retrofit = "2.9.0"
    const val room = "2.4.2"
    const val swipe = "1.1.0"
    const val timber = "5.0.1"
}